project:
  type: website
  pre-render: R/generate_param_reports.R

website:
  title: "Dep-wq-data-report"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - href: sites_qc.qmd
        
      - href: provider_sites_report.qmd
        text: Data Provider Reports
        
      - href: parameters.qmd
        text: WQ Parameter Reports
        
      - href: data_details.qmd
        text: Data Details
        
      - href: seacar_compare.qmd
        text: SEACAR Comparison
        
      - href: https://github.com/USF-IMARS/dep-wq-data-report
        text: Source Code on GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  cache: true

