project:
  type: website
  pre-render: R/generate_param_reports.R
website:
  title: "Dep-wq-data-report"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: parameters.qmd
        text: parameters
      - href: parameters_report.qmd
        text: WQ Params
      - href: sites_report.qmd
        text: Collection Sites

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



